// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkRhlaXqbPbYCai45Cc9Wo7cPasT62BfY',
    appId: '1:388900619387:web:a0734290bc47aa4fe98ede',
    messagingSenderId: '388900619387',
    projectId: 'biometri-app',
    authDomain: 'biometri-app.firebaseapp.com',
    storageBucket: 'biometri-app.appspot.com',
    measurementId: 'G-R7GP9Y6PPQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8jC_78cfavAQb0roxGd8xI-8QbF-wTAc',
    appId: '1:388900619387:android:753c4932407db9e2e98ede',
    messagingSenderId: '388900619387',
    projectId: 'biometri-app',
    storageBucket: 'biometri-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa43FLAFIA5Fueopc6x736zBHb1JQ30RY',
    appId: '1:388900619387:ios:a11ea8ac4c73a320e98ede',
    messagingSenderId: '388900619387',
    projectId: 'biometri-app',
    storageBucket: 'biometri-app.appspot.com',
    iosClientId: '388900619387-d8dh8a0s4m0t26jp1635dbb8dnsal3so.apps.googleusercontent.com',
    iosBundleId: 'com.mrezkys.presence',
  );
}
