// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfcKK9lH4AXCkYWfNVrQAMft8cOWR7PNk',
    appId: '1:1074133312441:web:abe42e7b05b283d3f54c68',
    messagingSenderId: '1074133312441',
    projectId: 'presence-82a2f',
    authDomain: 'presence-82a2f.firebaseapp.com',
    storageBucket: 'presence-82a2f.appspot.com',
    measurementId: 'G-K3HSPFTBWW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0YiyADvMCxuOmCIXLkvxhcM963IHq7IQ',
    appId: '1:1074133312441:android:8f852340e74d0e09f54c68',
    messagingSenderId: '1074133312441',
    projectId: 'presence-82a2f',
    storageBucket: 'presence-82a2f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjRvguA9XCr15Dh21Uw5DIyZpY5-xvttY',
    appId: '1:1074133312441:ios:1f2add810e2231bef54c68',
    messagingSenderId: '1074133312441',
    projectId: 'presence-82a2f',
    storageBucket: 'presence-82a2f.appspot.com',
    iosClientId: '1074133312441-u9lj57eemuekshib3v6oh7uafo7hm1b4.apps.googleusercontent.com',
    iosBundleId: 'com.mrezkys.presence',
  );
}
